### PR TITLE
cloudsql: Use a shorter cloudsql service account name to allow longer Kubeflow name

### PR DESCRIPTION
**Pull request by kindomLee**
fix the name length restriction #358

### CODE REVIEW

**Comment by zijianjoy** [comment]
Have you validated this change works?

We use this service account in the following files:

- https://github.com/kubeflow/gcp-blueprints/blob/d96b7fe4a95d306acc36387151947b27ea023a96/kubeflow/apps/pipelines/cloudsql/cnrm/iam.yaml
- https://github.com/kubeflow/gcp-blueprints/blob/d96b7fe4a95d306acc36387151947b27ea023a96/kubeflow/apps/pipelines/cloudsql/cnrm/proxy-gsa.yaml

Note: Even with the complete change, I think it will still cause potential breaking change for Kubeflow upgrade scenario. But let's focus on the first time installation scenario for now.

**Comment by kindomLee** [comment]
You are right, I will test the complete installation process in my environment and modify the files that are affected.

**Comment by kindomLee** [comment]
> Have you validated this change works?
> 
> We use this service account in the following files:
> 
> * https://github.com/kubeflow/gcp-blueprints/blob/d96b7fe4a95d306acc36387151947b27ea023a96/kubeflow/apps/pipelines/cloudsql/cnrm/iam.yaml
> * https://github.com/kubeflow/gcp-blueprints/blob/d96b7fe4a95d306acc36387151947b27ea023a96/kubeflow/apps/pipelines/cloudsql/cnrm/proxy-gsa.yaml
> 
> Note: Even with the complete change, I think it will still cause potential breaking change for Kubeflow upgrade scenario. But let's focus on the first time installation scenario for now.

I completed the installation process once using the default values and successfully logged in via google iap authentication

**Comment by zijianjoy** [comment]
/lgtm

Thank you for validating! But I think login is not enough to validate the change working. Because you need to use CloudSQL by running a Kubeflow Pipeline. 
LGTM on the change itself, pending final validation to provide approval.

**Comment by kindomLee** [comment]
image
I think we are good to go

**Comment by zijianjoy** [comment]
/approve

Thank you so much for the contribution!

**Pull request merged**
