### PR TITLE
Need to create the knative-serving namespace in the proper order

### PR DESCRIPTION
**Pull request by jlewi**
Related to #74

### CODE REVIEW

**Comment by jlewi** [comment]
/assign @Bobgy 

@ellistarn Would you mind LGTM'ing this? @Bobgy is in Shanghai ; probably won't be around for another 6-8 hours?

**Comment by ellistarn** [comment]
The syntax is throwing me
```
knative/~g_v1_namespace_knative-serving.yaml 
```
but I'll assume you know what you're doing. LGTM to add a knative namespace to install those resources in.
Additionally, we've had discussions about installing other components (i.e. KFServing) into their own namespaces. It may become slightly more challenging to maintain, but this is how the knative project does its namespaces, i.e. knative-serving and knative-eventing

**Comment by jlewi** [comment]
@ellistarn Thanks. The filenames are auto-generated by kustomize I think the name scheme for the files is something like "api <group>.<namespace>.<resource name>"

**Pull request merged**
