### PR TITLE
Move the private GKE docs to the website.

### PR DESCRIPTION
**Pull request by jlewi**
Related to kubeflow/website#1705

### CODE REVIEW

**Comment by jlewi** [comment]
Preview:
https://deploy-preview-2190--competent-brattain-de2d6d.netlify.app/docs/gke/private-clusters/

**Comment by Bobgy** [comment]
/hold
/lgtm
We should merge after the website PR is merged

**Comment by jlewi** [comment]
Website PR has been merged.

/hold cancel

**Comment by jlewi** [comment]
Merging manually since this isn't related to the test failure.

**Pull request merged**
