### PR TITLE
ASM: Upgrade ASM from 1.9.3 to 1.10.4. Fix #304

### LINKED ISSUE #304: Upgrade ASM to use the latest version (optional: explore install_asm -> asmcli) (2d)
Upgrade ASM from 1.9.3 to 1.10.4.

Optional: http://cloud/service-mesh/docs/unified-install/asmcli-overview
asmcli is the new tool that we plan to migrate over in the future, but there are many changes that are pending for graduating from asmcli Alpha. Keeping the note below so we can use as reference when asmcli is ready.

### PR DESCRIPTION
**Pull request by zijianjoy**
Fix #304.

- Upgrade ASM to the latest version.
- Move ASM upgrade guide from Makefile to README.
- Remove install_asm and asm packages, rely on user pulling from the source during deployment.
- Update code comments from previous PR feedback.
- Keep asmcli make rule exploration as the record in Makefile.

### CODE REVIEW

**Comment by Bobgy** [comment]
/lgtm
Thanks!

**Comment by pablofiumara** [comment]
@zijianjoy Can I ask you a question? If I execute 

`curl https://storage.googleapis.com/csm-artifacts/asm/STABLE_VERSIONS`

I get this:
```

1.9:install_asm_1.9
1.9:asm_vm_1.9
1.9.8-asm.6+config1:install_asm_1.9.8-asm.6-config1
1.9.8-asm.6+config1:asm_vm_1.9.8-asm.6-config1
1.9.8-asm.3+config1:install_asm_1.9.8-asm.3-config1
1.9.8-asm.3+config1:asm_vm_1.9.8-asm.3-config1
1.9.8-asm.1+config1:install_asm_1.9.8-asm.1-config1
1.9.8-asm.1+config1:asm_vm_1.9.8-asm.1-config1
1.9.6-asm.2+config1:install_asm_1.9.6-asm.2-config1
1.9.6-asm.2+config1:asm_vm_1.9.6-asm.2-config1
1.9.6-asm.1+config1:install_asm_1.9.6-asm.1-config1
1.9.6-asm.1+config1:asm_vm_1.9.6-asm.1-config1
1.9.3-asm.2+config2:install_asm_1.9.3-asm.2-config2
1.9.3-asm.2+config2:asm_vm_1.9.3-asm.2-config2
1.9.3-asm.2+config1:install_asm_1.9.3-asm.2-config1
1.9.3-asm.2+config1:asm_vm_1.9.3-asm.2-config1
1.9.2-asm.1+config4:install_asm_1.9.2-asm.1-config4
1.9.2-asm.1+config4:asm_vm_1.9.2-asm.1-config4
1.9.1-asm.1+config3:install_asm_1.9.1-asm.1-config3
1.9.1-asm.1+config3:asm_vm_1.9.1-asm.1-config3
1.9.1-asm.1+config2:install_asm_1.9.1-asm.1-config2
1.9.1-asm.1+config2:asm_vm_1.9.1-asm.1-config2
1.9.1-asm.1+config1:install_asm_1.9.1-asm.1-config1
1.9.1-asm.1+config1:asm_vm_1.9.1-asm.1-config1
1.8:install_asm_1.8
1.8.6-asm.8+config1:install_asm_1.8.6-asm.8-config1
1.8.6-asm.7+config1:install_asm_1.8.6-asm.7-config1
1.8.6-asm.5+config1:install_asm_1.8.6-asm.5-config1
1.8.6-asm.3+config1:install_asm_1.8.6-asm.3-config1
1.8.5-asm.2+config1:install_asm_1.8.5-asm.2-config1
1.8.3-asm.2+config3:install_asm_1.8.3-asm.2-config3
1.8.3-asm.2+config2:install_asm_1.8.3-asm.2-config2
1.8.3-asm.2+config1:install_asm_1.8.3-asm.2-config1
1.8.2-asm.2+config5:install_asm_1.8.2-asm.2-config5
1.8.2-asm.2+config4:install_asm_1.8.2-asm.2-config4
1.8.2-asm.2+config3:install_asm_1.8.2-asm.2-config3
1.8.2-asm.2+config2:install_asm_1.8.2-asm.2-config2
1.8.2-asm.2+config1:install_asm_1.8.2-asm.2-config1
1.8.1-asm.5+config4:install_asm_1.8.1-asm.5-config4
1.8.1-asm.5+config3:install_asm_1.8.1-asm.5-config3
1.8.1-asm.5+config2:install_asm_1.8.1-asm.5-config2
1.8.1-asm.5+config1:install_asm_1.8.1-asm.5-config1
1.7:install_asm_1.7
1.7.8-asm.8+config1:install_asm_1.7.8-asm.8-config1
1.7.8-asm.1+config1:install_asm_1.7.8-asm.1-config1
1.7.8-asm.10+config2:install_asm_1.7.8-asm.10-config2
1.7.8-asm.10+config1:install_asm_1.7.8-asm.10-config1
1.7.6-asm.1+config4:install_asm_1.7.6-asm.1-config4
1.7.6-asm.1+config3:install_asm_1.7.6-asm.1-config3
1.7.6-asm.1+config2:install_asm_1.7.6-asm.1-config2
1.7.6-asm.1+config1:install_asm_1.7.6-asm.1-config1
1.7.3-asm.6+config4:install_asm_1.7.3-asm.6-config4
1.7.3-asm.6+config3:install_asm_1.7.3-asm.6-config3
1.7.3-asm.6+config2:install_asm_1.7.3-asm.6-config2
1.11:install_asm_1.11
1.11:asm_vm_1.11
1.11.2-asm.17+config1-legacy:install_asm_1.11.2-asm.17-config1-legacy
1.11.2-asm.17+config1-legacy:asm_vm_1.11.2-asm.17-config1-legacy
1.10:install_asm_1.10
1.10:asm_vm_1.10
1.10.6-asm.2+config1:install_asm_1.10.6-asm.2-config1
1.10.6-asm.2+config1:asm_vm_1.10.6-asm.2-config1
1.10.6-asm.1+config1:install_asm_1.10.6-asm.1-config1
1.10.6-asm.1+config1:asm_vm_1.10.6-asm.1-config1
1.10.6-asm.0+config1:install_asm_1.10.6-asm.0-config1
1.10.6-asm.0+config1:asm_vm_1.10.6-asm.0-config1
1.10.4-asm.9+config1:install_asm_1.10.4-asm.9-config1
1.10.4-asm.9+config1:asm_vm_1.10.4-asm.9-config1
1.10.4-asm.6+config2:install_asm_1.10.4-asm.6-config2
1.10.4-asm.6+config2:asm_vm_1.10.4-asm.6-config2
1.10.4-asm.6+config1:install_asm_1.10.4-asm.6-config1
1.10.4-asm.6+config1:asm_vm_1.10.4-asm.6-config1
1.10.4-asm.14+config2:install_asm_1.10.4-asm.14-config2
1.10.4-asm.14+config2:asm_vm_1.10.4-asm.14-config2
1.10.4-asm.14+config1:install_asm_1.10.4-asm.14-config1
1.10.4-asm.14+config1:asm_vm_1.10.4-asm.14-config1
1.10.2-asm.3+config2:install_asm_1.10.2-asm.3-config2
1.10.2-asm.3+config2:asm_vm_1.10.2-asm.3-config2
1.10.2-asm.3+config1:install_asm_1.10.2-asm.3-config1
1.10.2-asm.3+config1:asm_vm_1.10.2-asm.3-config1
1.10.2-asm.2+config1:install_asm_1.10.2-asm.2-config1
1.10.2-asm.2+config1:asm_vm_1.10.2-asm.2-config1

```

None of those versions seems to be good for what GCP requests. I received the following message from GCP. What am I missing?


```
Upgrade to one of the following versions of Anthos Service Mesh:

If you’re using Anthos Service Mesh 1.13, upgrade to v1.13.4-asm.3.
If you’re using Anthos Service Mesh 1.12, upgrade to v1.12.7-asm.1.
If you’re using Anthos Service Mesh 1.11, upgrade to v1.11.8-asm.3.
If you're using Anthos Service Mesh v1.10 or below, your release has reached end of life and is no longer supported. These CVE fixes have not been backported. You should upgrade to ASM 1.11 or above.
```

**Comment by zijianjoy** [comment]
@pablofiumara Since ASM 1.10 is reaching end-of-life, you need to upgrade ASM to the newer version: https://github.com/kubeflow/gcp-blueprints/blob/master/kubeflow/asm/README.md

**Comment by pablofiumara** [comment]
@zijianjoy Thanks for your answer. Before I was using asm-193-2. It seems I should upgrade to v1.11.8-asm.3 according to GCP message. I executed the steps mentioned in the readme and now I have asm-1104-6. Is that version ok? I got it after setting ASM_PACKAGE_VERSION and INSTALL_ASM_SCRIPT_VERSION to the numbers found in master branch (this repository) - 1.10.4-asm.6+config2 and install_asm_1.10.4-asm.6-config2

**Comment by zijianjoy** [comment]
@pablofiumara Note that asm-1104-6 means it is `ASM 1.10.4`. I think it will soon be reaching the end of life, if not already deprecated. But if you have got the ASM 1.10.4 installed, then it is all good.

For validation: If you can open the Kubeflow Dashboard UI via an URL, and not authorized user cannot access UI, I think you are mostly okay.

**Comment by pablofiumara** [comment]
@zijianjoy Thanks again. How can I get ASM_PACKAGE_VERSION and INSTALL_ASM_SCRIPT_VERSION for v1.11.8-asm.3?

**Comment by zijianjoy** [comment]
@pablofiumara You can follow instruction in https://github.com/kubeflow/gcp-blueprints/blob/18bf45ad832712bc64bfd9428718dddc0823f8e1/kubeflow/asm/Makefile#L1-L5

**Comment by pablofiumara** [comment]
> @pablofiumara You can follow instruction in
> 
> https://github.com/kubeflow/gcp-blueprints/blob/18bf45ad832712bc64bfd9428718dddc0823f8e1/kubeflow/asm/Makefile#L1-L5

@zijianjoy Thanks for answering again. I followed those instructions. When I execute:

curl https://storage.googleapis.com/csm-artifacts/asm/STABLE_VERSIONS 

I get no meaningful 1.11 version. What should I do?

**Comment by zijianjoy** [comment]
@pablofiumara ASM has migrated to `asmcli` so they deprecated the old tool, you will need to follow their instruction for now https://cloud.google.com/service-mesh/v1.11/docs/unified-install/asmcli-overview#transitioning_to_asmcli. We will aim to implement a new integration in next release.

**Comment by pablofiumara** [comment]
> @pablofiumara ASM has migrated to `asmcli` so they deprecated the old tool, you will need to follow their instruction for now https://cloud.google.com/service-mesh/v1.11/docs/unified-install/asmcli-overview#transitioning_to_asmcli. We will aim to implement a new integration in next release.

@zijianjoy Thank you, it worked. Why is `asm-1134-4` installed if I type in the Makefile `1.13.4-asm.3+config1`? What am I missing? I ask number 3 but I get number 4

**Comment by pablofiumara** [comment]
@zijianjoy asm-1134-4 got installed but I cannot access Kubeflow dashboard anymore. Log says:

_Unable to fetch Pod CPU Utilization metrics: Permission monitoring.timeSeries.list denied (or the resource may not exist)._


I reverted as explained in the following link but dashboard still cannot be accessed. Do you know what is happening? https://cloud.google.com/service-mesh/docs/unified-install/upgrade#deploying_and_redeploying_workloads

**Comment by pablofiumara** [comment]
Fixed using this: https://github.com/kubeflow/gcp-blueprints/issues/343#issuecomment-1028488756

@zijianjoy Can you explain this, please? https://github.com/kubeflow/gcp-blueprints/pull/305#issuecomment-1154224712

**Comment by zijianjoy** [comment]
> > @pablofiumara ASM has migrated to `asmcli` so they deprecated the old tool, you will need to follow their instruction for now https://cloud.google.com/service-mesh/v1.11/docs/unified-install/asmcli-overview#transitioning_to_asmcli. We will aim to implement a new integration in next release.
> 
> @zijianjoy Thank you, it worked. Why is `asm-1134-4` installed if I type in the Makefile `1.13.4-asm.3+config1`? What am I missing? I ask number 3 but I get number 4

It feels like an ASM issue, you should probably contact https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages

**Pull request merged**
